name: 'Bash Echo Action'
description: 'A simple composite action that echoes a message using Bash'

runs:
  using: 'composite'
  steps:
    - name: Echo
      shell: bash
      run: |
        echo "pwned"
